eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8006
# Spring 日志策略
logging:
  level:
    com.baomidou.dynamic: info
    root: info
spring:
  application:
    name: ribbon-provider
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    connection-timeout: 15000
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:

