eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8003
spring:
  application:
    name: ribbon-consumer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    connection-timeout: 15000
    listener:
      # 最好不要在代码里写死配置信息，尽量使用这种方式也就是配置文件的方式
      # 在代码里使用 	${}	方式进行设置配置: ${spring.rabbitmq.listener.order.exchange.name}
#      order:
#        exchange:
#          durable: true
#          key: order.#
#          name: order-exchange
#          type: topic

      # 表示消费者消费成功消息以后需要手工的进行签收(ack)，默认为auto
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
    password: guest
    username: guest
    virtual-host: /