eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8005
spring:
  application:
    name: zuul-gateway

zuul:
  routes:
    ribbon-consumer:
      path: /ribbonconsumer/**
      service-id: ribbon-consumer
      stripPrefix: false
